### ISSUE TITLE
More indicative error messages

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/lambda-calculus#79] opened 2022-03-14 04:13 UTC
Running a program with no syntax error but type error gives runtime error like this:

```
TypeError: S.is-left(...) is not a function
    at Context.<anonymous> (file:///workspace/test.js:31:44)
    at processImmediate (node:internal/timers:464:21)
```

which is not helpful at all.

**Comment by JohanWiltink** [comment] 2022-03-14 13:57
The language itself is untyped, so type errors are impossible to generate from within the language. Encodings are outside of the known universe also.

That said, please specify `verbosity "Verbose"` and include relevant LC and JS source to reproduce the error, and full output; maybe something can be done on the JS part.

Also, just "not helpful" is not very helpful - what do you expect, what _would_ be helpful - while also being possible?

**Comment by Voileexperiments** [comment] 2022-03-15 04:20
> what do you expect, what would be helpful - while also being possible?

Any acceptable error messages and stack traces should point out the point of failure. (Unless it's a C++ segfault, which everyone hates with a passion.) All non-compile errors in LC only emits stack traces of the caller or the LC evaluator implementation. There are no information on the location in source code in which the error occurred, and the information on the involved terms. In other words, LC is nigh un-debuggable at the moment.

---

There are mostly 3 types of non-compiles errors (when `numEncoding` isn't involved anyway, since that causes recursive errors):

```
EvalError
    at runEval (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:342:83)
    at Object.result (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:328:14)
    at Context.<anonymous> (file:///workspace/test.js:29:36)
    at processImmediate (node:internal/timers:464:21)
```

When `()` is being evaluated (LHS or RHS)

```
TypeError: lastTerm is not a function
    at runEval (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:386:23)
    at result (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:328:14)
    at Context.<anonymous> (file:///workspace/test.js:28:58)
    at processImmediate (node:internal/timers:464:21)
```

When a value is being applied as LHS

```
TypeError: S.is-left(...) is not a function
    at Context.<anonymous> (file:///workspace/test.js:31:44)
    at processImmediate (node:internal/timers:464:21)
```

When user code calls a LC value

---

When there is a runtime error from LC, just like JS, I should know at least these things:

- Where did the application/evaluation happen (w/ line/char number)
- What is the LHS and RHS term, along with their environments
- (Optionally, or with limited depth) do this for LHS and RHS recursively

Otherwise I do not thing this language is ready for general use (which it happened; who the hell was writing CW katas with LC in this state and approved them??? Now everyone has to be subjected with complete lack of error information).

> That said, please specify `verbosity "Verbose"` and include relevant LC and JS source to reproduce the error, and full output; maybe something can be done on the JS part.

Verbosity does not affect error messages and stack traces from LC.

**Comment by Kacarott** [comment] 2022-03-15 08:41
### Type 1 error (Evaluating Undefined)

Currently, for all verbosities greater than `Calm`,  the `EvalError` is accompanied by a seperate stderr message, such as:
```
eval: evaluating undefined inside definition of will-throw
```
Also, for `Verbose`, a simple stack trace is also printed (it is printed twice, currently, for some reason. Will fix.)

I am in favour of moving this message to be inside the error message itself, and removing the `at runEval... etc.` stack trace, which is not useful.

### Type 2 error (value applied as LHS)

I agree, that this could be improved reasonably easily.  I will work on this today.

### Type 3 error (Value is not a function)

This error happens outside of LC evaluation, and is a difficult one to address. In such a case, the compiled LC term has correctly received input and finished computation, returning some native JS value (for example a string). The tests however, did not expect a function to be returned, and have tried to call that value, again, causing the error.

Since the LC has worked correctly, and the failure happens simply in testing, I do not see how this one could be improved, just as we cannot provide better error messages for authors writing `true(false)`.

One single idea I had, would be to replace all input JS values (which are not functions) with a function that would throw a more appropriate error. The actual passed value could potentially be accessed by an attribute, or something. Then the return value from LC evaluation would *always* be a function, be that one that throws (in a way we control), or not. However, I do not like this idea as it adds yet more confusing behaviour, difficulty in authoring, and is just all around unpleasant.

**Comment by Voileexperiments** [comment] 2022-03-16 02:24
> One single idea I had, would be to replace all input JS values (which are not functions) with a function that would throw a more appropriate error. The actual passed value could potentially be accessed by an attribute, or something. Then the return value from LC evaluation would always be a function, be that one that throws (in a way we control), or not. However, I do not like this idea as it adds yet more confusing behaviour, difficulty in authoring, and is just all around unpleasant.

Since LC term should always stay lazy, LC terms should really stay as-is *unless it is actually evaluated*, I don't see what's the problem here. I'd say I instead find the current language behaviour extremely confusing: JS numbers being implicitly, forcefully lifted to LC numerals; partially eager evaluations; etc.

**Comment by JohanWiltink** [comment] 2022-04-14 09:40
> > That said, please specify `verbosity "Verbose"` and include relevant LC and JS source to reproduce the error, and full output; maybe something can be done on the JS part.
> 
> Verbosity does not affect error messages and stack traces from LC.

If you're not going to respond to requests, be incorrect, be confusing the issue and continually move the goalposts, this issue will not be solved.

Closing.

**Closed as completed by JohanWiltink** 2022-04-14 09:40 UTC
Labels: improvement

**Comment by MatthijsBlom** [comment] 2025-04-03 01:11
> That said, please specify `verbosity "Verbose"` and include relevant LC and JS source to reproduce the error, and full output; maybe something can be done on the JS part.

Here is some code & logs that exhibits this problem:

```
nil = \ c n . n
cons = \ h t . \ c n . c h (t c n)

id = \ x . x
poly = \ op e n . n (\ k r x . k (op r x)) id e

# list-n :: Church -> { a -> ... } -> List a
list-n = poly cons nil

# foldr :: (a -> b -> b) -> b -> List a -> b
foldr = \ fn x xs . xs (\ h t . fn h (foldr fn x t)) x
```
```javascript
import { assert, LC, getSolution } from "./lc-test.js";

LC.configure({ purity: "LetRec", numEncoding: "Church", verbosity: "Verbose" });
const { "list-n":listN, foldr } = LC.compile(getSolution());

const toArr = foldr(v=>a=>[v, ...a])([]);

describe("Fixed tests", () => {
  it("list-n", () => {
    assert.deepEqual(toArr(listN(3)("a")("b")("c")), ["a", "b", "c"]);
  });
});
```
```
compiled nil = \ c n . n
compiled cons = \ h t c n . c h (t c n)
compiled id = \ x . x
compiled poly = \ op e n . n (\ k r x . k (op r x)) id e
   using id = \ x . x
compiled list-n = poly cons nil
   using poly = \ op e n . n (\ k r x . k (op r x)) id e
   using cons = \ h t c n . c h (t c n)
   using nil = \ c n . n
compiled foldr = \ fn x xs . xs (\ h t . fn h (foldr fn x t)) x
```
```
TypeError: lastTerm is not a function
    at runEval (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:400:18)
    at result (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:359:16)
    at Context.<anonymous> (file:///workspace/test.js:10:22)
    at processImmediate (node:internal/timers:464:21)
```

The problem being that this error message gives no indication of where to look in my code.

**Comment by JohanWiltink** [comment] 2025-04-03 20:05
>    assert.deepEqual(toArr(listN(4)("a")("b")("c")), ["a", "b", "c"]);

I'm guessing you mean `.. listN(3) ..`; otherwise I can't reproduce the error message.

You have the `cons` of a Church-encoded list and the `foldr` of a Scott encoded list. Which one should the error message point to? The `poly` doesn't disambiguate your encoding; it seems to be wrong for both encodings. Or should it point to `poly`, or to `list-n` ? How do you even decide where the actual error is?

It is conceivably possible to change the "not a function" `TypeError` to a custom error with a message showing what `lastTerm` _is_ ( being something other than a function ) instead of stupidly applying an argument and triggering the JS `Error` ( by checking something is a `function` before doing that ). This will probably not be implemented anytime soon though, sorry; development is stalled ATM.

**Comment by MatthijsBlom** [comment] 2025-04-03 22:33
> I'm guessing you mean `.. listN(3) ..`; otherwise I can't reproduce the error message.

Yes, I meant `3`. The `4` was a remnant of variations I tried to generate different error messages.

> [...] Which one should the error message point to? [...] Or should it point to `poly`, or to `list-n` ? How do you even decide where the actual error is?

Neither, and neither. I don't think giving named terms special treatment makes much sense, in &lambda;-calculus.

There is no error _in_ my code. (Even though my code probably is at odds with my intent.) Rather, the runtime environment got into trouble while interpreting it.[^1] I could not reasonably ask for anything more, I think, than to be shown a (sub)sequence of steps that led to the trouble.

[^1]: If it had supplied functions of sufficient arity as values to operate upon, there wouldn't have been runtime errors. Sure, the result still wouldn't match my intent, but that is not a problem _in_ my code.

> It is conceivably possible to change the "not a function" `TypeError` to a custom error with a message showing what `lastTerm` _is_ ( being something other than a function ) [...]

That sounds like it could already be very helpful!

Though perhaps not in my particular situation, as it seems in my case `lastTerm` might be `undefined` and it is not obvious where it comes from.
